class_name ColdExposureManager
extends Node
## Manages cold exposure and its effects
## Extremities lose heat faster than core
##
## Design Philosophy:
## - Cold is shown through visuals (frost, breath) not meters
## - Extremity cold affects specific actions
## - Core cold is systemic danger
## - Activity generates some heat

# =============================================================================
# SIGNALS
# =============================================================================

signal cold_exposure_changed(core: float, extremities: Dictionary)
signal extremity_warning(body_part: GameEnums.BodyPart, severity: float)
signal hypothermia_onset()
signal frostbite_risk(body_part: GameEnums.BodyPart)
signal shivering_started()
signal shivering_stopped()

# =============================================================================
# CONFIGURATION
# =============================================================================

@export_group("Heat Loss")
## Base heat loss rate per second at 0°C
@export var base_heat_loss: float = 0.002
## Heat loss per degree below freezing
@export var temp_heat_loss_factor: float = 0.0002
## Wind chill multiplier
@export var wind_chill_multiplier: float = 1.5
## Wet clothing multiplier
@export var wet_multiplier: float = 2.0

@export_group("Heat Gain")
## Heat generated by activity (per activity level)
@export var activity_heat_rate: float = 0.003
## Shivering heat generation
@export var shivering_heat_rate: float = 0.001

@export_group("Extremity Rates")
## Extremity heat loss multiplier vs core
@export var extremity_loss_multiplier: float = 2.0
## Extremity warming rate from core
@export var extremity_warm_rate: float = 0.001

@export_group("Thresholds")
## Cold level for shivering
@export var shivering_threshold: float = 0.3
## Cold level for extremity warning
@export var extremity_warning_threshold: float = 0.5
## Cold level for frostbite risk
@export var frostbite_threshold: float = 0.8
## Cold level for hypothermia
@export var hypothermia_threshold: float = 0.7

# =============================================================================
# STATE
# =============================================================================

## Reference to body state
var body_state: BodyState

## Temperature system reference
var temperature_system: TemperatureSystem

## Current activity level (generates heat)
var activity_level: float = 0.0

## Is player wet
var is_wet: bool = false

## Clothing insulation level (0-1)
var insulation: float = 0.7

## Is shivering
var is_shivering: bool = false

## Frostbite warnings issued
var frostbite_warnings: Dictionary = {}


# =============================================================================
# INITIALIZATION
# =============================================================================

func _ready() -> void:
	ServiceLocator.get_service_async("TemperatureSystem", _on_temperature_ready)
	ServiceLocator.register_service("ColdExposureManager", self)


func _on_temperature_ready(service: Object) -> void:
	temperature_system = service as TemperatureSystem


## Set body state reference
func set_body_state(state: BodyState) -> void:
	body_state = state


# =============================================================================
# UPDATE
# =============================================================================

func _physics_process(delta: float) -> void:
	if body_state == null:
		return

	var heat_balance := _calculate_heat_balance()

	# Apply to core
	_apply_core_exposure(heat_balance, delta)

	# Apply to extremities (faster loss)
	_apply_extremity_exposure(heat_balance, delta)

	# Emit updates
	cold_exposure_changed.emit(body_state.cold_exposure, body_state.extremity_cold)

	# Check thresholds
	_check_thresholds()


func _calculate_heat_balance() -> float:
	# Positive = warming, Negative = cooling
	var balance := 0.0

	# Base heat loss
	balance -= base_heat_loss

	# Temperature effect
	if temperature_system:
		var temp := temperature_system.get_feels_like()
		if temp < 0.0:
			balance -= absf(temp) * temp_heat_loss_factor

	# Insulation helps
	balance *= 1.0 - insulation * 0.7

	# Wet is very bad
	if is_wet:
		balance *= wet_multiplier

	# Activity generates heat
	balance += activity_level * activity_heat_rate

	# Shivering generates some heat
	if is_shivering:
		balance += shivering_heat_rate

	return balance


func _apply_core_exposure(heat_balance: float, delta: float) -> void:
	if heat_balance < 0:
		# Cooling
		body_state.add_cold_exposure(-heat_balance * delta, GameEnums.BodyPart.TORSO)
	else:
		# Warming - reduce cold exposure
		body_state.cold_exposure = maxf(0.0, body_state.cold_exposure - heat_balance * delta)


func _apply_extremity_exposure(heat_balance: float, delta: float) -> void:
	var extremities := [
		GameEnums.BodyPart.LEFT_HAND,
		GameEnums.BodyPart.RIGHT_HAND,
		GameEnums.BodyPart.LEFT_FOOT,
		GameEnums.BodyPart.RIGHT_FOOT
	]

	for part in extremities:
		var part_cold: float = body_state.extremity_cold.get(part, 0.0)

		if heat_balance < 0:
			# Extremities cool faster
			var loss := -heat_balance * extremity_loss_multiplier * delta

			# Gloves/boots help
			loss *= _get_extremity_protection(part)

			part_cold = minf(1.0, part_cold + loss)
		else:
			# Warming from core
			var core_warm := body_state.cold_exposure < part_cold
			if core_warm:
				part_cold = maxf(0.0, part_cold - extremity_warm_rate * delta)

		body_state.extremity_cold[part] = part_cold


func _get_extremity_protection(part: GameEnums.BodyPart) -> float:
	# Would integrate with gear system
	# For now, base protection
	match part:
		GameEnums.BodyPart.LEFT_HAND, GameEnums.BodyPart.RIGHT_HAND:
			return 0.7  # Gloves
		GameEnums.BodyPart.LEFT_FOOT, GameEnums.BodyPart.RIGHT_FOOT:
			return 0.5  # Boots
		_:
			return 1.0


func _check_thresholds() -> void:
	# Shivering
	var should_shiver := body_state.cold_exposure > shivering_threshold
	if should_shiver != is_shivering:
		is_shivering = should_shiver
		if is_shivering:
			shivering_started.emit()
		else:
			shivering_stopped.emit()

	# Hypothermia
	if body_state.cold_exposure >= hypothermia_threshold:
		hypothermia_onset.emit()

	# Extremity warnings
	for part in body_state.extremity_cold:
		var cold: float = body_state.extremity_cold[part]

		if cold >= frostbite_threshold:
			if not frostbite_warnings.get(part, false):
				frostbite_warnings[part] = true
				frostbite_risk.emit(part)
		elif cold >= extremity_warning_threshold:
			extremity_warning.emit(part, cold)
		else:
			frostbite_warnings[part] = false


# =============================================================================
# INPUT FROM OTHER SYSTEMS
# =============================================================================

## Set activity level (from movement system)
func set_activity_level(level: float) -> void:
	activity_level = clampf(level, 0.0, 1.0)


## Set wet state
func set_wet(wet: bool) -> void:
	is_wet = wet


## Set insulation level (from gear system)
func set_insulation(level: float) -> void:
	insulation = clampf(level, 0.0, 1.0)


## Apply sudden cold exposure (falling in water, etc.)
func apply_sudden_exposure(amount: float) -> void:
	if body_state:
		body_state.cold_exposure = minf(1.0, body_state.cold_exposure + amount)

		# Extremities hit harder
		for part in body_state.extremity_cold:
			body_state.extremity_cold[part] = minf(1.0,
				body_state.extremity_cold[part] + amount * 1.5)

		cold_exposure_changed.emit(body_state.cold_exposure, body_state.extremity_cold)


# =============================================================================
# QUERIES
# =============================================================================

## Get core cold exposure
func get_core_cold() -> float:
	if body_state:
		return body_state.cold_exposure
	return 0.0


## Get worst extremity cold
func get_worst_extremity_cold() -> float:
	if body_state == null:
		return 0.0

	var worst := 0.0
	for part in body_state.extremity_cold:
		worst = maxf(worst, body_state.extremity_cold[part])
	return worst


## Get specific extremity cold
func get_extremity_cold(part: GameEnums.BodyPart) -> float:
	if body_state:
		return body_state.extremity_cold.get(part, 0.0)
	return 0.0


## Get hand dexterity modifier
func get_hand_dexterity() -> float:
	var hand_cold := maxf(
		get_extremity_cold(GameEnums.BodyPart.LEFT_HAND),
		get_extremity_cold(GameEnums.BodyPart.RIGHT_HAND)
	)
	return 1.0 - hand_cold * 0.7


## Get foot stability modifier
func get_foot_stability() -> float:
	var foot_cold := maxf(
		get_extremity_cold(GameEnums.BodyPart.LEFT_FOOT),
		get_extremity_cold(GameEnums.BodyPart.RIGHT_FOOT)
	)
	return 1.0 - foot_cold * 0.5


## Check if hypothermic
func is_hypothermic() -> bool:
	return get_core_cold() >= hypothermia_threshold


## Check if any frostbite risk
func has_frostbite_risk() -> bool:
	return get_worst_extremity_cold() >= frostbite_threshold


## Get visual effects intensity (frost on screen, etc.)
func get_frost_effect_intensity() -> float:
	return clampf(get_core_cold() * 1.5, 0.0, 1.0)


## Get breath vapor visibility (for diegetic cold display)
func get_breath_visibility() -> float:
	if temperature_system:
		return temperature_system.get_breath_visibility()
	return get_core_cold() * 0.5


## Get summary for debug/UI
func get_summary() -> Dictionary:
	return {
		"core_cold": get_core_cold(),
		"worst_extremity": get_worst_extremity_cold(),
		"is_shivering": is_shivering,
		"is_hypothermic": is_hypothermic(),
		"hand_dexterity": get_hand_dexterity(),
		"foot_stability": get_foot_stability(),
		"frost_effect": get_frost_effect_intensity()
	}
